require_relative 'global_values'
require_relative 'manufacturer'
require_relative 'instance_counter'
require_relative 'base_menu'
require_relative 'wagon'
require_relative 'cargo_wagon'
require_relative 'passenger_wagon'
require_relative 'train'
require_relative 'station'
require_relative 'passenger_train'
require_relative 'cargo_train'
require_relative 'route'
require_relative 'change_route'
require_relative 'primary'
require_relative 'interface'
require_relative 'apendix_menu_stations'
require_relative 'menu_stations'
require_relative 'apendix_menu_train'
require_relative 'menu_trains'

@menu_main = Interface.new
@menu_main.start
